# Generated by Django 2.1.7 on 2019-10-26 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20191025_2346'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='post',
            name='title_image',
            field=models.ImageField(blank=True, null=True, upload_to='blog_title_image/'),
        ),
    ]
